#! /usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
my $event = "docker-update";

# Demo code below

## docker-update templates to expand
#
foreach (qw(
       /etc/sysconfig/docker
       /etc/sysconfig/docker-storage
       /home/e-smith/files/docker/configs/docker-compose.yml
    ))

{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update
    docker-update
    ));
}


##--------------------------------------------------
## actions for docker-update event
##--------------------------------------------------
#
# ONLY if we have an actual actions script to do more
#
# event_link("docker-update", $event, "10");
#

## Runlevel init links.
service_link_enhanced("docker", "S95", "7");
service_link_enhanced("docker", "K21", "6");
service_link_enhanced("docker", "K21", "0");
service_link_enhanced("docker", "K21", "1");

# restart masq on docker-update

safe_symlink("adjust", "root/etc/e-smith/events/$event/services2adjust/masq");

# Old stuff left as a reminder
#
## Set up generic logfile timestamp renaming/symlinking
#
#foreach (qw(
#    /var/log/pluto/pluto.log
#    ))
#{
#    safe_touch "root/etc/e-smith/events/logrotate/logfiles2timestamp/$_";
#}
#
##--------------------------------------------------
## actions for logrotate event
##--------------------------------------------------
#
#$event = "logrotate";
#
#safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/ipsec");
