#! /usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

# Which event to add it to ?

# htpd will expanded with any of these events anyway

foreach (qw(
       /etc/sysconfig/docker
       /etc/rc.d/init.d/masq
    ))
{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update

    ));
}


# Runlevel init links.
service_link_enhanced("ipsec", "S95", "7");
service_link_enhanced("ipsec", "K21", "6");
service_link_enhanced("ipsec", "K21", "0");
service_link_enhanced("ipsec", "K21", "1");

# Set up generic logfile timestamp renaming/symlinking
# Not sure what dcker logs to normally so guessing here

foreach (qw(
    /var/log/docket/docker.log
    ))
{
    safe_touch "root/etc/e-smith/events/logrotate/logfiles2timestamp/$_";
}

#--------------------------------------------------
# actions for logrotate event
#--------------------------------------------------

$event = "logrotate";
